### ISSUE TITLE
Plugin doesn't ingest messages on Graylog 2.4.7

### ISSUE THREAD

**Issue by atarallo** [exabrial/graylog-plugin-openwire#2]
I've installed version 1.0.2 on Graylog 2.4.7. I'm intending to download messages from ActiveMQ 5. I've connected successfully to the queue, but messages don't get into graylog. I've found this messages on graylog server log:

` 019-06-21T11:27:52.425-03:00 ERROR [ActiveMQMessageConsumer] ID:srvhZZZZ-43728-1561066133943-13:1:1:1 Exception while processing message: ID:srvhXXXX-44195-1551968170890-5:7:-1:1:15229
java.lang.ClassCastException: org.apache.activemq.command.ActiveMQBytesMessage cannot be cast to javax.jms.TextMessage
at com.github.exabrial.graylog.OpenwireConsumer$2.onMessage(OpenwireConsumer.java:61) ~[graylog-plugin-openwire-1.0.2.jar:?]
at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404) [graylog-plugin-openwire-1.0.2.jar:?]
at org.apache.activemq.ActiveMQMessageConsumer.iterate(ActiveMQMessageConsumer.java:1575) [graylog-plugin-openwire-1.0.2.jar:?]
at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:191) [graylog-plugin-openwire-1.0.2.jar:?]
at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [graylog-plugin-openwire-1.0.2.jar:?]
at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [graylog-plugin-openwire-1.0.2.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

**Comment by exabrial** [comment]
So it looks like your inbound message is a BytesMessage, not a TextMessage. How are you sending data to the queue?

**Comment by atarallo** [comment]
I collect syslog messages, that are sent to logstash. Logstash connect to ActiveMQ via STOMP.

**Comment by exabrial** [comment]
I see! I remember that now all the ActiveMQ non-native adapters pass
the message as a BytesMessage not a TextMessage.

This is a pretty easy fix actually... it's the holiday here, we're
celebrating our independence, but I could actually get this done in a few
minutes. Look for a release I the next few days.

**Comment by atarallo** [comment]
Thanks for taking time to review this. I´ll be lloking forward to test the new release.

**Comment by exabrial** [comment]
Here's a patch if you want to give it a whirl:

```
diff --git a/src/main/java/com/github/exabrial/graylog/OpenwireConsumer.java b/src/main/java/com/github/exabrial/graylog/OpenwireConsumer.java
index d7333eb..665e303 100644
--- a/src/main/java/com/github/exabrial/graylog/OpenwireConsumer.java
+++ b/src/main/java/com/github/exabrial/graylog/OpenwireConsumer.java
@@ -5,13 +5,11 @@
 import java.util.concurrent.TimeUnit;
 import java.util.concurrent.atomic.AtomicLong;
 
+import javax.jms.BytesMessage;
 import javax.jms.Connection;
 import javax.jms.Destination;
-import javax.jms.ExceptionListener;
 import javax.jms.JMSException;
-import javax.jms.Message;
 import javax.jms.MessageConsumer;
-import javax.jms.MessageListener;
 import javax.jms.Session;
 import javax.jms.TextMessage;
 
@@ -39,12 +37,7 @@
 		this.sourceInput = sourceInput;
 		this.openwireTransport = openwireTransport;
 
-		scheduler.scheduleAtFixedRate(new Runnable() {
-			@Override
-			public void run() {
-				lastSecBytesRead.set(lastSecBytesReadTmp.getAndSet(0));
-			}
-		}, 1, 1, TimeUnit.SECONDS);
+		scheduler.scheduleAtFixedRate(() -> lastSecBytesRead.set(lastSecBytesReadTmp.getAndSet(0)), 1, 1, TimeUnit.SECONDS);
 	}
 
 	public void run() throws JMSException {
@@ -54,24 +47,31 @@
 		Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
 		Destination destination = session.createQueue(queue);
 		MessageConsumer consumer = session.createConsumer(destination);
-		consumer.setMessageListener(new MessageListener() {
-			@Override
-			public void onMessage(Message message) {
-				try {
-					TextMessage textMessage = (TextMessage) message;
-					String body = textMessage.getText();
-					totalBytesRead.addAndGet(body.length());
-					lastSecBytesReadTmp.addAndGet(body.length());
-					final RawMessage rawMessage = new RawMessage(body.getBytes(StandardCharsets.UTF_8));
-					if (openwireTransport.isThrottled()) {
-						openwireTransport.blockUntilUnthrottled();
-					}
-					sourceInput.processRawMessage(rawMessage);
-				} catch (JMSException exception) {
-					Logger log = LoggerFactory.getLogger(getClass());
-					log.error("onMessage() error", exception);
-					throw new RuntimeException(exception);
+		consumer.setMessageListener(message -> {
+			try {
+				String body;
+				if (message instanceof TextMessage) {
+				TextMessage textMessage = (TextMessage) message;
+					body = textMessage.getText();
+				}else	if (message instanceof BytesMessage) {
+					BytesMessage bytesMessage = (BytesMessage) message;
+					byte[] bodyBytes = new byte[(int) bytesMessage.getBodyLength()];
+					bytesMessage.readBytes(bodyBytes);
+					body = new String(bodyBytes);
+				}else {
+					throw new RuntimeException("unsupported message type:"+message.getClass());
 				}
+				totalBytesRead.addAndGet(body.length());
+				lastSecBytesReadTmp.addAndGet(body.length());
+				final RawMessage rawMessage = new RawMessage(body.getBytes(StandardCharsets.UTF_8));
+				if (openwireTransport.isThrottled()) {
+					openwireTransport.blockUntilUnthrottled();
+				}
+				sourceInput.processRawMessage(rawMessage);
+			} catch (JMSException exception) {
+				Logger log = LoggerFactory.getLogger(getClass());
+				log.error("onMessage() error", exception);
+				throw new RuntimeException(exception);
 			}
 		});
 	}
@@ -80,12 +80,9 @@
 		ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactory(brokerUrl);
 		connection = connectionFactory.createConnection();
 		connection.start();
-		connection.setExceptionListener(new ExceptionListener() {
-			@Override
-			public void onException(JMSException exception) {
-				Logger log = LoggerFactory.getLogger(getClass());
-				log.error("onException() error", exception);
-			}
+		connection.setExceptionListener(exception -> {
+			Logger log = LoggerFactory.getLogger(getClass());
+			log.error("onException() error", exception);
 		});
 	}
 
```

**Comment by exabrial** [comment]
Give the new release a whirl. I don't have a great way to test it, unfortunately, but the code change is simple enough.

**Comment by atarallo** [comment]
Thanks again for taking time to review this issue. I´ll be testing this today.

**Comment by atarallo** [comment]
Tested both INPUT RAW and Syslog, both work. For the latter I have to set the switch allow_override_date to true.

**Comment by exabrial** [comment]
Nice! Glad to hear! enjoy
